# Generated by Django 4.0.2 on 2022-04-11 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allresume',
            table='all_resume',
        ),
        migrations.AlterModelTable(
            name='resumetemplatelist',
            table='resume_template_list',
        ),
        migrations.AlterModelTable(
            name='useraddress',
            table='user_address',
        ),
        migrations.AlterModelTable(
            name='userdetails',
            table='user_details',
        ),
        migrations.AlterModelTable(
            name='usereducation',
            table='user_education',
        ),
        migrations.AlterModelTable(
            name='userhobby',
            table='user_hobby',
        ),
        migrations.AlterModelTable(
            name='userlanguage',
            table='user_lang',
        ),
        migrations.AlterModelTable(
            name='userresume',
            table='user_resume',
        ),
        migrations.AlterModelTable(
            name='userskill',
            table='user_skill',
        ),
        migrations.AlterModelTable(
            name='usersocialmediahandles',
            table='user_social_media',
        ),
        migrations.AlterModelTable(
            name='userworkexp',
            table='user_work_exp',
        ),
    ]
