# Generated by Django 4.0.2 on 2022-04-11 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_allresume_table_alter_resumetemplatelist_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='social_media_handles',
        ),
    ]
