# Generated by Django 4.0.2 on 2022-04-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_remove_userdetails_social_media_handles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumetemplatelist',
            old_name='template',
            new_name='template_css',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='address',
            new_name='house_street',
        ),
        migrations.AddField(
            model_name='resumetemplatelist',
            name='template_html',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumetemplatelist',
            name='template_js',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
