# Generated by Django 4.0.2 on 2022-04-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_rename_template_resumetemplatelist_template_css_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='country',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddress',
            name='state',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
