# Generated by Django 4.0.2 on 2022-04-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_useraddress_country_useraddress_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_img'),
        ),
    ]
