# Generated by Django 4.0.3 on 2022-05-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_alter_userdetails_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='job_role',
            field=models.CharField(max_length=40),
        ),
    ]
