# Generated by Django 4.0.3 on 2022-05-14 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_alter_userdetails_job_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='country',
        ),
    ]
